["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/main.cairo",
]
DiamondCut = [
    "src/ERC2535/DiamondCut.cairo",
]
