["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
Diamond = [
    "src/ERC2535/Diamond.cairo",
]
DiamondCut = [
    "src/ERC2535/DiamondCut.cairo",
]
BFR = [
    "src/main/BFR/BFR.cairo"
]
TCF = [
    "src/main/TCF/TCF.cairo"
]
ERC1155 = [
    "src/ERC1155/ERC1155.cairo"
]
