[project]
protostar-version = "0.7.0"
lib-path = "lib"

[contracts]
Bootstrapper = ["src/bootstrap/Bootstrapper.cairo"]
BFR = ["src/zkode/Storage/BFR/BFR.cairo"]
FlobDB = ["src/zkode/Storage/FlobDB.cairo"]
StarkShell = ["src/zkode/starkshell/StarkShell.cairo"]
Diamond = ["src/zkode/ERC2535/Diamond.cairo"]
DiamondCut = ["src/zkode/ERC2535/DiamondCut.cairo"]
ERC1155 = ["src/zkode/ERC1155/ERC1155.cairo"]
ERC20 = ["src/zkode/ERC20/ERC20.cairo"]
ERC5114 = ["src/zkode/ERC5114/ERC5114.cairo"]
ERC721 = ["src/zkode/ERC721/ERC721.cairo"]
UniversalMetadata = ["src/zkode/UniversalMetadata/UniversalMetadata.cairo"]

[build]
cairo-path = ["./lib/cairo_streams/src/"]

[test]
cairo-path = ["./lib/cairo_streams/src/"]

