[project]
protostar-version = "0.8"
lib-path = "lib"

[contracts]
Bootstrapper = ["src/bootstrap/Bootstrapper.cairo"]
FeltMap = ["src/components/facets/storage/feltmap/FeltMap.cairo"]
FlobDB = ["src/components/facets/storage/flobdb/FlobDB.cairo"]
StarkShell = ["src/components/facets/starkshell/StarkShell.cairo"]
Diamond = ["src/components/diamond/Diamond.cairo"]
DiamondCut = ["src/components/facets/upgradability/DiamondCut.cairo"]
ERC1155 = ["src/components/facets/token/erc1155/ERC1155.cairo"]
ERC20 = ["src/components/facets/token/erc20/ERC20.cairo"]
ERC5114 = ["src/components/facets/token/erc5114/ERC5114.cairo"]
ERC721 = ["src/components/facets/token/erc721/ERC721.cairo"]
UniversalMetadata = ["src/components/facets/metadata/metadata/UniversalMetadata.cairo"]

[build]
cairo-path = ["./lib/cairo_streams/src/"]

[test]
cairo-path = ["./lib/cairo_streams/src/"]

