["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
Diamond = [
    "src/ERC2535/Diamond.cairo",
]
DiamondCut = [
    "src/ERC2535/DiamondCut.cairo",
]
