["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
ZKLANG = [
    "src/zklang/ZKlang.cairo"
]
Arithmetic.zklang = [
    "src/zklang/Arithmetic.zklang.cairo"
]
Diamond = [
    "src/ERC2535/Diamond.cairo",
]
DiamondCut = [
    "src/ERC2535/DiamondCut.cairo",
]
BFR = [
    "src/main/BFR/BFR.cairo"
]
TCF = [
    "src/main/TCF/TCF.cairo"
]
ERC1155 = [
    "src/ERC1155/ERC1155.cairo"
]
ERC20 = [
    "src/ERC20/ERC20.cairo"
]
ERC5114 = [
    "src/ERC5114/ERC5114.cairo"
]
ERC721 = [
    "src/ERC721/ERC721.cairo"
]
UniversalMetadata = [
    "src/UniversalMetadata/UniversalMetadata.cairo"
]
UniversalMint = [
    "src/UniversalMint/UniversalMint.cairo"
]
